# Generated by Django 4.2.22 on 2025-08-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_order_items_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='price_per_item',
        ),
    ]
