# Generated by Django 4.2.22 on 2025-08-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_order_delivery_time_remove_order_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
