# Generated by Django 4.2.22 on 2025-08-08 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('placed', 'Order Placed'), ('assigned', 'Assigned to Delivery Partner'), ('picked_up', 'Picked Up'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='out_for_delivery_at',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deliverypartner')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='core.deliverypartner'),
        ),
    ]
