# Generated by Django 4.2.22 on 2025-08-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_deliverypartner_alter_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverypartner',
            old_name='is_available',
            new_name='is_online',
        ),
    ]
