# Generated by Django 4.2.22 on 2025-08-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_is_available_deliverypartner_is_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='assigned_partner',
            new_name='assigned_to',
        ),
    ]
