# Generated by Django 4.2.22 on 2025-08-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_assigned_partner_order_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='out_for_delivery_at',
        ),
    ]
